spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  type-aliases-package: com.qs.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept8001
    prefer-ip-address: true
info:
  app.name: com.qs.microservicecloud
  company.name: www.qs.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

mybatis:
  type-aliases-package: com.qs.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept8001
    prefer-ip-address: true
info:
  app.name: com.qs.microservicecloud
  company.name: www.qs.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}